"use client";

import {
  Brain,
  Briefcase,
  FileText,
  Sparkles,
  Target,
  TrendingUp,
} from "lucide-react";

import FeatureCard from "./FeatureCard";

const features = [
  {
    icon: <Brain size={30} />,
    title: "AI CV Analysis",
    description:
      "Receive a complete ATS analysis powered by Artificial Intelligence.",
  },
  {
    icon: <Target size={30} />,
    title: "ATS Score",
    description:
      "Know exactly how recruiters and ATS systems evaluate your resume.",
  },
  {
    icon: <Briefcase size={30} />,
    title: "Job Matching",
    description:
      "Discover the best jobs according to your experience and skills.",
  },
  {
    icon: <TrendingUp size={30} />,
    title: "Salary Estimation",
    description:
      "Estimate your market value using AI and labor market data.",
  },
  {
    icon: <FileText size={30} />,
    title: "CV Optimization",
    description:
      "Improve your CV with concrete recommendations generated by AI.",
  },
  {
    icon: <Sparkles size={30} />,
    title: "Career Assistant",
    description:
      "Your intelligent assistant for interviews, applications and career growth.",
  },
];

export default function FeaturesSection() {
  return (
    <section className="bg-[#F8FAFC] py-28">
      <div className="mx-auto max-w-7xl px-6">

        <div className="mb-20 text-center">
          <h2 className="text-5xl font-black text-[#1F2937]">
            Everything You Need
          </h2>

          <p className="mt-6 text-lg text-stone-600">
            One platform. One AI. Everything for your career.
          </p>
        </div>


        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => (
            <FeatureCard
              key={feature.title}
              icon={feature.icon}
              title={feature.title}
              description={feature.description}
            />
          ))}
        </div>

      </div>
    </section>
  );
}